### ISSUE TITLE
OpenCL-HPP broken after the merge of #251

### ISSUE THREAD

**Issue by illuhad** [KhronosGroup/OpenCL-Headers#255]
Not sure if the primary issue is in OpenCL-HPP (from KhronosGroup/OpenCL-CLHPP) or OpenCL-Headers (KhronosGroup/OpenCL-Headers), but it seems since #251 was merged, OpenCL-HPP no longer compiles. This currently breaks AdaptiveCpp, which fetches these repositories at build time.

Reverting OpenCL-Headers to c860bb5 fixes the issue.

Here's the compiler output:
```
In file included from /tmp/unihd-sycl-ci-jarvis-0/actions-runner/_work/AdaptiveCpp/AdaptiveCpp/include/hipSYCL/runtime/ocl/ocl_event.hpp:32:
/tmp/unihd-sycl-ci-jarvis-0/actions-runner/_work/AdaptiveCpp/AdaptiveCpp/build/_deps/ocl-cxx-headers-src/include/CL/opencl.hpp:7198:20: error: use of undeclared identifier 'CL_EXTERNAL_MEMORY_HANDLE_D3D11_TEXTURE_KHR'
    D3D11Texture = CL_EXTERNAL_MEMORY_HANDLE_D3D11_TEXTURE_KHR,
                   ^
/tmp/unihd-sycl-ci-jarvis-0/actions-runner/_work/AdaptiveCpp/AdaptiveCpp/build/_deps/ocl-cxx-headers-src/include/CL/opencl.hpp:7201:17: error: use of undeclared identifier 'CL_EXTERNAL_MEMORY_HANDLE_D3D12_HEAP_KHR'
    D3D12Heap = CL_EXTERNAL_MEMORY_HANDLE_D3D12_HEAP_KHR,
                ^
/tmp/unihd-sycl-ci-jarvis-0/actions-runner/_work/AdaptiveCpp/AdaptiveCpp/build/_deps/ocl-cxx-headers-src/include/CL/opencl.hpp:7199:23: error: use of undeclared identifier 'CL_EXTERNAL_MEMORY_HANDLE_D3D11_TEXTURE_KMT_KHR'
    D3D11TextureKmt = CL_EXTERNAL_MEMORY_HANDLE_D3D11_TEXTURE_KMT_KHR,
                      ^
/tmp/unihd-sycl-ci-jarvis-0/actions-runner/_work/AdaptiveCpp/AdaptiveCpp/build/_deps/ocl-cxx-headers-src/include/CL/opencl.hpp:7202:21: error: use of undeclared identifier 'CL_EXTERNAL_MEMORY_HANDLE_D3D12_RESOURCE_KHR'
    D3D12Resource = CL_EXTERNAL_MEMORY_HANDLE_D3D12_RESOURCE_KHR,
                    ^
/tmp/unihd-sycl-ci-jarvis-0/actions-runner/_work/AdaptiveCpp/AdaptiveCpp/build/_deps/ocl-cxx-headers-src/include/CL/opencl.hpp:7201:17: error: use of undeclared identifier 'CL_EXTERNAL_MEMORY_HANDLE_D3D12_HEAP_KHR'
    D3D12Heap = CL_EXTERNAL_MEMORY_HANDLE_D3D12_HEAP_KHR,
                ^
/tmp/unihd-sycl-ci-jarvis-0/actions-runner/_work/AdaptiveCpp/AdaptiveCpp/build/_deps/ocl-cxx-headers-src/include/CL/opencl.hpp:7202:21: error: use of undeclared identifier 'CL_EXTERNAL_MEMORY_HANDLE_D3D12_RESOURCE_KHR'
    D3D12Resource = CL_EXTERNAL_MEMORY_HANDLE_D3D12_RESOURCE_KHR,
                    ^
```

**Comment by bashbaug** [comment]
That's embarassing.  I'll fix this in OpenCL-CLHPP.
